# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="74ff1bce-7190-4409-ab41-8e80b7b29d0d"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - a.elyzarov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
